### PR TITLE
Add NCSS 2k17 memes

### PR DESCRIPTION
**Pull request by lyneca**
get some memes into you

### CODE REVIEW

**Comment by tgsergeant** [comment]
:hot_pepper::hot_pepper::hot_pepper: 👌 👌 👌 

thanks for adding the one of Ben doing 🆒  lanyard tricks, this is my absolute favourite part of the video

can you please add the new files to `MEMES` at https://github.com/tgsergeant/hotspicyme.me/blob/master/static/js/main.js#L1 so they actually show up in the site?

**Comment by lyneca** [comment]
Will do

**Comment by lyneca** [comment]
Should be okay now

**Comment by tgsergeant** [comment]
looks 👌👌👌 to me

gonna merge and then try to remember how to deploy.

i'll ping here when it's all done

**Comment by tgsergeant** [comment]
good content:

screenshot_20170128-123511

thanks for contributing!

**Pull request merged**
